export const mbtiTypes = {
  INTJ: {
    name: "Mimar",
    nickname: "Her şey için bir planı olan, yaratıcı ve stratejik düşünürler",
    characteristics: [
      "Rasyonel ve hızlı düşünen",
      "Bağımsız ve kararlı",
      "Yüksek standartlara sahip ve analitik",
      "Yaratıcı ve içgörülü",
      "Kararlı ve inatçı",
    ],
    strengths: [
      "Stratejik planlama",
      "Bağımsız düşünme",
      "Rasyonel karar verme",
      "İçgörülü analiz",
      "Sürekli kendini geliştirme",
    ],
    weaknesses: [
      "Aşırı eleştirel",
      "Duygulara karşı kayıtsız",
      "Mükemmeliyetçi eğilimler",
      "Duyguları ifade etmekte zorluk",
      "Kibirli görünebilir",
    ],
    careers: [
      "Bilimsel araştırmacı",
      "Sistem mühendisi",
      "Stratejik planlamacı",
      "Yatırım bankacısı",
      "Üniversite profesörü",
    ],
  },
  INTP: {
    name: "Mantıkçı",
    nickname: "Bilgi için doyumsuz bir susuzluğa sahip yenilikçi mucitler",
    characteristics: [
      "Analitik ve objektif",
      "Soyut düşünme",
      "Orijinal ve yaratıcı",
      "Açık fikirli",
      "Fikirler konusunda hevesli",
    ],
    strengths: [
      "Mantıksal akıl yürütme",
      "Yaratıcı problem çözme",
      "Objektif analiz",
      "Entelektüel merak",
      "Uyum sağlayabilirlik",
    ],
    weaknesses: [
      "Pratik konularda zorluk",
      "Aşırı düşünme",
      "Sosyal olarak kopuk",
      "Erteleme",
      "Kurallara uymakta zorluk",
    ],
    careers: ["Yazılım geliştirici", "Matematikçi", "Filozof", "Mimar", "Araştırma bilimcisi"],
  },
  ENTJ: {
    name: "Komutan",
    nickname: "Cesur, yaratıcı ve güçlü iradeli liderler",
    characteristics: [
      "Verimli ve enerjik",
      "Özgüvenli",
      "Stratejik düşünme",
      "Karizmatik liderlik",
      "Güçlü iradeli ve kararlı",
    ],
    strengths: ["Doğal liderlik", "Stratejik planlama", "Verimlilik", "Özgüven", "Kararlılık"],
    weaknesses: ["Sabırsızlık", "İnatçılık", "Kibir", "Duyarsızlık", "Hoşgörüsüzlük"],
    careers: ["Yönetici", "Girişimci", "Yönetim danışmanı", "Avukat", "Siyasi lider"],
  },
  ENTP: {
    name: "Tartışmacı",
    nickname: "Entelektüel bir meydan okumaya karşı koyamayan akıllı ve meraklı düşünürler",
    characteristics: [
      "Yenilikçi ve yaratıcı",
      "Bilgili",
      "Mükemmel iletişimciler",
      "Enerjik ve uyarıcı",
      "Hızlı düşünenler",
    ],
    strengths: [
      "Yaratıcı problem çözme",
      "Uyum sağlayabilirlik",
      "Mükemmel iletişim",
      "Tartışma becerileri",
      "Hızlı düşünme",
    ],
    weaknesses: ["Tartışmacı", "Duyarsız", "Hoşgörüsüz", "Odaklanmada zorluk", "Rutinden hoşlanmama"],
    careers: ["Girişimci", "Avukat", "Kreatif direktör", "Danışman", "Mühendis"],
  },
  INFJ: {
    name: "Savunucu",
    nickname: "Sessiz ve gizemli, ancak çok ilham verici ve yorulmak bilmeyen idealistler",
    characteristics: [
      "İçgörülü ve sezgisel",
      "İlkeli ve değer odaklı",
      "Yaratıcı ve sanatsal",
      "Geleceğe yönelik",
      "Derin ve karmaşık",
    ],
    strengths: [
      "Derin içgörü",
      "Yaratıcı düşünme",
      "Güçlü inançlar",
      "İlham verme",
      "Başkalarının gelişimine yardımcı olma",
    ],
    weaknesses: [
      "Mükemmeliyetçilik",
      "Başkalarına yardım ederken tükenmişlik",
      "Eleştiriye karşı hassasiyet",
      "Aşırı özel olma",
      "Çatışmadan kaçınma",
    ],
    careers: ["Danışman", "Psikolog", "Yazar", "İK yöneticisi", "Profesör"],
  },
  INFP: {
    name: "Arabulucu",
    nickname: "Şiirsel, nazik ve özgeci insanlar, her zaman iyi bir davaya yardım etmeye hazır",
    characteristics: [
      "İdealist ve sadık",
      "Yaratıcı ve sanatsal",
      "Meraklı ve uyumlu",
      "Tutkulu ve enerjik",
      "Değerlere adanmış",
    ],
    strengths: ["Empati ve şefkat", "Yaratıcılık", "Açık fikirlilik", "Tutku ve adanmışlık", "Potansiyeli görebilme"],
    weaknesses: [
      "Pratik olmayan idealizm",
      "Her şeyi kişisel algılama",
      "Kendini izole etme",
      "Odaklanmamış",
      "Eleştiriye karşı hassasiyet",
    ],
    careers: ["Yazar", "Grafik tasarımcı", "Danışman", "Sosyal hizmet uzmanı", "Sanatçı"],
  },
  ENFJ: {
    name: "Protagonist",
    nickname: "Dinleyicilerini büyüleyebilen karizmatik ve ilham verici liderler",
    characteristics: [
      "Karizmatik ve ilham verici",
      "Özgeci ve empatik",
      "Güvenilir ve doğal liderler",
      "Mükemmel iletişimciler",
      "Cesaretlendirici ve destekleyici",
    ],
    strengths: ["Doğal liderlik", "Karizma", "Empati", "Güvenilirlik", "İletişim becerileri"],
    weaknesses: [
      "İdealizm",
      "Aşırı hassasiyet",
      "Dalgalanan özgüven",
      "Başkalarına yardım ederken tükenmişlik",
      "Zor kararlar vermekte zorluk",
    ],
    careers: ["Öğretmen", "İK direktörü", "Yaşam koçu", "Sivil toplum kuruluşu yöneticisi", "Danışman"],
  },
  ENFP: {
    name: "Kampanyacı",
    nickname: "Her zaman gülümsemek için bir neden bulabilen coşkulu, yaratıcı ve sosyal özgür ruhlar",
    characteristics: [
      "Coşkulu ve enerjik",
      "Mükemmel insan ilişkileri",
      "Yaratıcı ve hayal gücü yüksek",
      "Meraklı ve gözlemci",
      "Tutkulu ve enerjik",
    ],
    strengths: ["İletişim becerileri", "Coşku", "Yaratıcılık", "Uyum sağlayabilirlik", "İnsan ilişkileri"],
    weaknesses: ["Zayıf pratik beceriler", "Odaklanmada zorluk", "Aşırı düşünme", "Duygusal", "Aşırı bağımsız"],
    careers: ["Gazeteci", "Aktör", "Pazarlama uzmanı", "Etkinlik planlayıcısı", "Psikolog"],
  },
  ISTJ: {
    name: "Lojistikçi",
    nickname: "Güvenilirliğinden şüphe edilemeyen pratik ve gerçekçi bireyler",
    characteristics: [
      "Pratik ve gerçekçi",
      "Güvenilir ve sorumlu",
      "Sadık ve çalışkan",
      "Geleneksel ve düzenli",
      "Doğrudan ve dürüst",
    ],
    strengths: ["Dürüstlük ve bütünlük", "Sorumluluk", "Pratik beceriler", "Mantıksal düşünme", "Organizasyon"],
    weaknesses: ["İnatçı", "Duyarsız", "Her zaman kurallara bağlı", "Yargılayıcı", "Duyguları ifade etmekte zorluk"],
    careers: ["Muhasebeci", "Askeri subay", "Hakim", "Finansal analist", "Ofis yöneticisi"],
  },
  ISFJ: {
    name: "Savunucu",
    nickname: "Her zaman sevdiklerini korumaya hazır, çok adanmış ve sıcak koruyucular",
    characteristics: [
      "Destekleyici ve güvenilir",
      "Gözlemci ve dikkatli",
      "Sabırlı ve sadık",
      "Çalışkan ve sorumlu",
      "Geleneksel ve aile odaklı",
    ],
    strengths: ["Destekleyici doğa", "Güvenilirlik", "Pratik beceriler", "Sabır", "Detaylara dikkat"],
    weaknesses: [
      "Aşırı alçakgönüllü",
      "Her şeyi kişisel algılama",
      "Değişime direnç",
      "Aşırı sorumluluk alma",
      "Duyguları bastırma",
    ],
    careers: ["Hemşire", "İlkokul öğretmeni", "İdari asistan", "Sosyal hizmet uzmanı", "İç mimar"],
  },
  ESTJ: {
    name: "Yönetici",
    nickname: "Mükemmel yöneticiler, şeyleri veya insanları yönetmede rakipsiz",
    characteristics: [
      "Organize ve pratik",
      "Sadık ve dürüst",
      "Adanmış ve güçlü iradeli",
      "Geleneksel ve muhafazakar",
      "Güçlü liderlik becerileri",
    ],
    strengths: ["Organizasyon", "Adanmışlık", "Dürüstlük", "Güçlü liderlik", "Güvenilirlik"],
    weaknesses: [
      "Esnek olmama",
      "İnatçılık",
      "Yargılayıcı",
      "Duyguları ifade etmekte zorluk",
      "Sosyal statüye aşırı odaklanma",
    ],
    careers: ["İşletme yöneticisi", "Polis memuru", "Askeri subay", "Hakim", "Finans yöneticisi"],
  },
  ESFJ: {
    name: "Konsül",
    nickname: "Her zaman yardım etmeye hazır, olağanüstü ilgili, sosyal ve popüler insanlar",
    characteristics: [
      "İlgili ve destekleyici",
      "Sosyal ve dışa dönük",
      "Pratik ve geleneksel",
      "Sadık ve güvenilir",
      "Hassas ve sıcak",
    ],
    strengths: [
      "Güçlü pratik beceriler",
      "Başkalarına karşı duyarlılık",
      "Güvenilirlik",
      "Güçlü görev duygusu",
      "İnsanları bağlama becerisi",
    ],
    weaknesses: [
      "Sosyal statü konusunda endişeli",
      "Esnek olmama",
      "Yenilik yapmaya isteksizlik",
      "Eleştiriye karşı hassasiyet",
      "Genellikle bağımlı",
    ],
    careers: ["Hemşire", "Öğretmen", "Sosyal hizmet uzmanı", "İK uzmanı", "Etkinlik planlayıcısı"],
  },
  ISTP: {
    name: "Virtüöz",
    nickname: "Cesur ve pratik deneyimciler, her türlü aracın ustası",
    characteristics: [
      "İyimser ve enerjik",
      "Yaratıcı ve pratik",
      "Spontane ve rasyonel",
      "Bağımsız ve özgüvenli",
      "Akranlarına sadık",
    ],
    strengths: ["İyimserlik", "Yaratıcılık", "Pratik düşünme", "Kriz yönetimi", "Uyum sağlayabilirlik"],
    weaknesses: ["İnatçı", "Duyarsız", "Risk eğilimli", "Kolay sıkılan", "Bağlılıktan hoşlanmama"],
    careers: ["Mekanik", "Mühendis", "Pilot", "Marangoz", "Adli bilimci"],
  },
  ISFP: {
    name: "Maceracı",
    nickname: "Her zaman yeni bir şey keşfetmeye ve deneyimlemeye hazır esnek ve çekici sanatçılar",
    characteristics: [
      "Sanatsal ve yaratıcı",
      "Çekici ve hassas",
      "Hayal gücü yüksek ve meraklı",
      "Tutkulu ve enerjik",
      "Öngörülemeyen ve spontane",
    ],
    strengths: ["Sanatsal yetenek", "Yaratıcılık", "Tutku", "Merak", "Çekicilik"],
    weaknesses: ["Aşırı bağımsız", "Öngörülemeyen", "Kolay stres olan", "Aşırı rekabetçi", "Dalgalanan özgüven"],
    careers: ["Sanatçı", "Tasarımcı", "Fotoğrafçı", "Besteci", "Moda tasarımcısı"],
  },
  ESTP: {
    name: "Girişimci",
    nickname: "Gerçekten uçlarda yaşamaktan keyif alan akıllı, enerjik ve çok algılayıcı insanlar",
    characteristics: [
      "Enerjik ve aktif",
      "Rasyonel ve pratik",
      "Orijinal ve algılayıcı",
      "Sosyal ve eğlenceli",
      "Spontane ve becerikli",
    ],
    strengths: ["Cesur risk alma", "Rasyonellik", "Özgünlük", "Algılayıcılık", "Sosyallik"],
    weaknesses: ["Sabırsız", "Risk eğilimli", "Yapılandırılmamış", "Meydan okuyan", "Duyarsız"],
    careers: ["Girişimci", "Pazarlamacı", "Dedektif", "Paramedik", "Satış temsilcisi"],
  },
  ESFP: {
    name: "Eğlendirici",
    nickname: "Spontane, enerjik ve coşkulu insanlar - onların etrafında hayat asla sıkıcı değildir",
    characteristics: [
      "Coşkulu ve spontane",
      "Mükemmel insan ilişkileri",
      "Pratik ve gözlemci",
      "Destekleyici ve cömert",
      "Çekici ve popüler",
    ],
    strengths: ["Cesaret", "Özgünlük", "Estetik ve gösteriş", "Pratik beceriler", "Gözlem becerileri"],
    weaknesses: ["Hassas", "Çatışmadan kaçınan", "Kolay sıkılan", "Zayıf uzun vadeli planlama", "Odaklanmada zorluk"],
    careers: ["Aktör", "Çocuk bakıcısı", "Etkinlik planlayıcısı", "Satış temsilcisi", "Tur rehberi"],
  },
}
